// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: majong_rpc.proto

package mahjong.mode.proto;

public interface CalculateResultOrBuilder extends
        // @@protoc_insertion_point(interface_extends:majong_rpc.CalculateResult)
        com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 能够吃的牌
     * </pre>
     * <p>
     * <code>repeated int32 chi = 1;</code>
     */
    java.util.List<java.lang.Integer> getChiList();

    /**
     * <pre>
     * 能够吃的牌
     * </pre>
     * <p>
     * <code>repeated int32 chi = 1;</code>
     */
    int getChiCount();

    /**
     * <pre>
     * 能够吃的牌
     * </pre>
     * <p>
     * <code>repeated int32 chi = 1;</code>
     */
    int getChi(int index);

    /**
     * <pre>
     * 能够碰的牌
     * </pre>
     * <p>
     * <code>repeated int32 peng = 2;</code>
     */
    java.util.List<java.lang.Integer> getPengList();

    /**
     * <pre>
     * 能够碰的牌
     * </pre>
     * <p>
     * <code>repeated int32 peng = 2;</code>
     */
    int getPengCount();

    /**
     * <pre>
     * 能够碰的牌
     * </pre>
     * <p>
     * <code>repeated int32 peng = 2;</code>
     */
    int getPeng(int index);

    /**
     * <pre>
     * 能够杠的牌
     * </pre>
     * <p>
     * <code>repeated int32 gang = 3;</code>
     */
    java.util.List<java.lang.Integer> getGangList();

    /**
     * <pre>
     * 能够杠的牌
     * </pre>
     * <p>
     * <code>repeated int32 gang = 3;</code>
     */
    int getGangCount();

    /**
     * <pre>
     * 能够杠的牌
     * </pre>
     * <p>
     * <code>repeated int32 gang = 3;</code>
     */
    int getGang(int index);

    /**
     * <pre>
     * 能够胡的牌
     * </pre>
     * <p>
     * <code>repeated int32 hu = 4;</code>
     */
    java.util.List<java.lang.Integer> getHuList();

    /**
     * <pre>
     * 能够胡的牌
     * </pre>
     * <p>
     * <code>repeated int32 hu = 4;</code>
     */
    int getHuCount();

    /**
     * <pre>
     * 能够胡的牌
     * </pre>
     * <p>
     * <code>repeated int32 hu = 4;</code>
     */
    int getHu(int index);

    /**
     * <pre>
     * 能自摸的牌
     * </pre>
     * <p>
     * <code>repeated int32 zimo = 5;</code>
     */
    java.util.List<java.lang.Integer> getZimoList();

    /**
     * <pre>
     * 能自摸的牌
     * </pre>
     * <p>
     * <code>repeated int32 zimo = 5;</code>
     */
    int getZimoCount();

    /**
     * <pre>
     * 能自摸的牌
     * </pre>
     * <p>
     * <code>repeated int32 zimo = 5;</code>
     */
    int getZimo(int index);

    /**
     * <pre>
     * 附加操作
     * </pre>
     * <p>
     * <code>bytes adjunct = 6;</code>
     */
    com.google.protobuf.ByteString getAdjunct();
}
