// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: majong_rpc.proto

package mahjong.mode.proto;

/**
 * <pre>
 * 申请麻将游戏的逻辑计算
 * </pre>
 * <p>
 * Protobuf type {@code majong_rpc.CalculateData}
 */
public final class CalculateData extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:majong_rpc.CalculateData)
        CalculateDataOrBuilder {
    // Use CalculateData.newBuilder() to construct.
    private CalculateData(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
    }

    private CalculateData() {
        allocid_ = 0;
        adjunct_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
        return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }

    private CalculateData(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        int mutable_bitField0_ = 0;
        try {
            boolean done = false;
            while (!done) {
                int tag = input.readTag();
                switch (tag) {
                    case 0:
                        done = true;
                        break;
                    default: {
                        if (!input.skipField(tag)) {
                            done = true;
                        }
                        break;
                    }
                    case 8: {

                        allocid_ = input.readInt32();
                        break;
                    }
                    case 18: {
                        mahjong.mode.proto.MajongPlayerData.Builder subBuilder = null;
                        if (player_ != null) {
                            subBuilder = player_.toBuilder();
                        }
                        player_ = input.readMessage(mahjong.mode.proto.MajongPlayerData.parser(), extensionRegistry);
                        if (subBuilder != null) {
                            subBuilder.mergeFrom(player_);
                            player_ = subBuilder.buildPartial();
                        }

                        break;
                    }
                    case 26: {

                        adjunct_ = input.readBytes();
                        break;
                    }
                }
            }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
            throw new com.google.protobuf.InvalidProtocolBufferException(
                    e).setUnfinishedMessage(this);
        } finally {
            makeExtensionsImmutable();
        }
    }

    public static final com.google.protobuf.Descriptors.Descriptor
    getDescriptor() {
        return mahjong.mode.proto.MajongRpcProto.internal_static_majong_rpc_CalculateData_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
    internalGetFieldAccessorTable() {
        return mahjong.mode.proto.MajongRpcProto.internal_static_majong_rpc_CalculateData_fieldAccessorTable
                .ensureFieldAccessorsInitialized(
                        mahjong.mode.proto.CalculateData.class, mahjong.mode.proto.CalculateData.Builder.class);
    }

    public static final int ALLOCID_FIELD_NUMBER = 1;
    private int allocid_;

    /**
     * <code>int32 allocid = 1;</code>
     */
    public int getAllocid() {
        return allocid_;
    }

    public static final int PLAYER_FIELD_NUMBER = 2;
    private mahjong.mode.proto.MajongPlayerData player_;

    /**
     * <code>.majong_rpc.MajongPlayerData player = 2;</code>
     */
    public boolean hasPlayer() {
        return player_ != null;
    }

    /**
     * <code>.majong_rpc.MajongPlayerData player = 2;</code>
     */
    public mahjong.mode.proto.MajongPlayerData getPlayer() {
        return player_ == null ? mahjong.mode.proto.MajongPlayerData.getDefaultInstance() : player_;
    }

    /**
     * <code>.majong_rpc.MajongPlayerData player = 2;</code>
     */
    public mahjong.mode.proto.MajongPlayerDataOrBuilder getPlayerOrBuilder() {
        return getPlayer();
    }

    public static final int ADJUNCT_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString adjunct_;

    /**
     * <pre>
     * 附加的一些判断条件
     * </pre>
     * <p>
     * <code>bytes adjunct = 3;</code>
     */
    public com.google.protobuf.ByteString getAdjunct() {
        return adjunct_;
    }

    private byte memoizedIsInitialized = -1;

    public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
            throws java.io.IOException {
        if (allocid_ != 0) {
            output.writeInt32(1, allocid_);
        }
        if (player_ != null) {
            output.writeMessage(2, getPlayer());
        }
        if (!adjunct_.isEmpty()) {
            output.writeBytes(3, adjunct_);
        }
    }

    public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (allocid_ != 0) {
            size += com.google.protobuf.CodedOutputStream
                    .computeInt32Size(1, allocid_);
        }
        if (player_ != null) {
            size += com.google.protobuf.CodedOutputStream
                    .computeMessageSize(2, getPlayer());
        }
        if (!adjunct_.isEmpty()) {
            size += com.google.protobuf.CodedOutputStream
                    .computeBytesSize(3, adjunct_);
        }
        memoizedSize = size;
        return size;
    }

    private static final long serialVersionUID = 0L;

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
            return true;
        }
        if (!(obj instanceof mahjong.mode.proto.CalculateData)) {
            return super.equals(obj);
        }
        mahjong.mode.proto.CalculateData other = (mahjong.mode.proto.CalculateData) obj;

        boolean result = true;
        result = result && (getAllocid()
                == other.getAllocid());
        result = result && (hasPlayer() == other.hasPlayer());
        if (hasPlayer()) {
            result = result && getPlayer()
                    .equals(other.getPlayer());
        }
        result = result && getAdjunct()
                .equals(other.getAdjunct());
        return result;
    }

    @java.lang.Override
    public int hashCode() {
        if (memoizedHashCode != 0) {
            return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + ALLOCID_FIELD_NUMBER;
        hash = (53 * hash) + getAllocid();
        if (hasPlayer()) {
            hash = (37 * hash) + PLAYER_FIELD_NUMBER;
            hash = (53 * hash) + getPlayer().hashCode();
        }
        hash = (37 * hash) + ADJUNCT_FIELD_NUMBER;
        hash = (53 * hash) + getAdjunct().hashCode();
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
    }

    public static mahjong.mode.proto.CalculateData parseFrom(
            java.nio.ByteBuffer data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static mahjong.mode.proto.CalculateData parseFrom(
            java.nio.ByteBuffer data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static mahjong.mode.proto.CalculateData parseFrom(
            com.google.protobuf.ByteString data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static mahjong.mode.proto.CalculateData parseFrom(
            com.google.protobuf.ByteString data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static mahjong.mode.proto.CalculateData parseFrom(byte[] data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static mahjong.mode.proto.CalculateData parseFrom(
            byte[] data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static mahjong.mode.proto.CalculateData parseFrom(java.io.InputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input);
    }

    public static mahjong.mode.proto.CalculateData parseFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static mahjong.mode.proto.CalculateData parseDelimitedFrom(java.io.InputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseDelimitedWithIOException(PARSER, input);
    }

    public static mahjong.mode.proto.CalculateData parseDelimitedFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }

    public static mahjong.mode.proto.CalculateData parseFrom(
            com.google.protobuf.CodedInputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input);
    }

    public static mahjong.mode.proto.CalculateData parseFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() {
        return newBuilder();
    }

    public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
    }

    public static Builder newBuilder(mahjong.mode.proto.CalculateData prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
                ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
    }

    /**
     * <pre>
     * 申请麻将游戏的逻辑计算
     * </pre>
     * <p>
     * Protobuf type {@code majong_rpc.CalculateData}
     */
    public static final class Builder extends
            com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
            // @@protoc_insertion_point(builder_implements:majong_rpc.CalculateData)
            mahjong.mode.proto.CalculateDataOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return mahjong.mode.proto.MajongRpcProto.internal_static_majong_rpc_CalculateData_descriptor;
        }

        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return mahjong.mode.proto.MajongRpcProto.internal_static_majong_rpc_CalculateData_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            mahjong.mode.proto.CalculateData.class, mahjong.mode.proto.CalculateData.Builder.class);
        }

        // Construct using mahjong.mode.proto.CalculateData.newBuilder()
        private Builder() {
            maybeForceBuilderInitialization();
        }

        private Builder(
                com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            super(parent);
            maybeForceBuilderInitialization();
        }

        private void maybeForceBuilderInitialization() {
            if (com.google.protobuf.GeneratedMessageV3
                    .alwaysUseFieldBuilders) {
            }
        }

        public Builder clear() {
            super.clear();
            allocid_ = 0;

            if (playerBuilder_ == null) {
                player_ = null;
            } else {
                player_ = null;
                playerBuilder_ = null;
            }
            adjunct_ = com.google.protobuf.ByteString.EMPTY;

            return this;
        }

        public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
            return mahjong.mode.proto.MajongRpcProto.internal_static_majong_rpc_CalculateData_descriptor;
        }

        public mahjong.mode.proto.CalculateData getDefaultInstanceForType() {
            return mahjong.mode.proto.CalculateData.getDefaultInstance();
        }

        public mahjong.mode.proto.CalculateData build() {
            mahjong.mode.proto.CalculateData result = buildPartial();
            if (!result.isInitialized()) {
                throw newUninitializedMessageException(result);
            }
            return result;
        }

        public mahjong.mode.proto.CalculateData buildPartial() {
            mahjong.mode.proto.CalculateData result = new mahjong.mode.proto.CalculateData(this);
            result.allocid_ = allocid_;
            if (playerBuilder_ == null) {
                result.player_ = player_;
            } else {
                result.player_ = playerBuilder_.build();
            }
            result.adjunct_ = adjunct_;
            onBuilt();
            return result;
        }

        public Builder clone() {
            return (Builder) super.clone();
        }

        public Builder setField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                Object value) {
            return (Builder) super.setField(field, value);
        }

        public Builder clearField(
                com.google.protobuf.Descriptors.FieldDescriptor field) {
            return (Builder) super.clearField(field);
        }

        public Builder clearOneof(
                com.google.protobuf.Descriptors.OneofDescriptor oneof) {
            return (Builder) super.clearOneof(oneof);
        }

        public Builder setRepeatedField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                int index, Object value) {
            return (Builder) super.setRepeatedField(field, index, value);
        }

        public Builder addRepeatedField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                Object value) {
            return (Builder) super.addRepeatedField(field, value);
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
            if (other instanceof mahjong.mode.proto.CalculateData) {
                return mergeFrom((mahjong.mode.proto.CalculateData) other);
            } else {
                super.mergeFrom(other);
                return this;
            }
        }

        public Builder mergeFrom(mahjong.mode.proto.CalculateData other) {
            if (other == mahjong.mode.proto.CalculateData.getDefaultInstance()) return this;
            if (other.getAllocid() != 0) {
                setAllocid(other.getAllocid());
            }
            if (other.hasPlayer()) {
                mergePlayer(other.getPlayer());
            }
            if (other.getAdjunct() != com.google.protobuf.ByteString.EMPTY) {
                setAdjunct(other.getAdjunct());
            }
            onChanged();
            return this;
        }

        public final boolean isInitialized() {
            return true;
        }

        public Builder mergeFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            mahjong.mode.proto.CalculateData parsedMessage = null;
            try {
                parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                parsedMessage = (mahjong.mode.proto.CalculateData) e.getUnfinishedMessage();
                throw e.unwrapIOException();
            } finally {
                if (parsedMessage != null) {
                    mergeFrom(parsedMessage);
                }
            }
            return this;
        }

        private int allocid_;

        /**
         * <code>int32 allocid = 1;</code>
         */
        public int getAllocid() {
            return allocid_;
        }

        /**
         * <code>int32 allocid = 1;</code>
         */
        public Builder setAllocid(int value) {

            allocid_ = value;
            onChanged();
            return this;
        }

        /**
         * <code>int32 allocid = 1;</code>
         */
        public Builder clearAllocid() {

            allocid_ = 0;
            onChanged();
            return this;
        }

        private mahjong.mode.proto.MajongPlayerData player_ = null;
        private com.google.protobuf.SingleFieldBuilderV3<
                mahjong.mode.proto.MajongPlayerData, mahjong.mode.proto.MajongPlayerData.Builder, mahjong.mode.proto.MajongPlayerDataOrBuilder> playerBuilder_;

        /**
         * <code>.majong_rpc.MajongPlayerData player = 2;</code>
         */
        public boolean hasPlayer() {
            return playerBuilder_ != null || player_ != null;
        }

        /**
         * <code>.majong_rpc.MajongPlayerData player = 2;</code>
         */
        public mahjong.mode.proto.MajongPlayerData getPlayer() {
            if (playerBuilder_ == null) {
                return player_ == null ? mahjong.mode.proto.MajongPlayerData.getDefaultInstance() : player_;
            } else {
                return playerBuilder_.getMessage();
            }
        }

        /**
         * <code>.majong_rpc.MajongPlayerData player = 2;</code>
         */
        public Builder setPlayer(mahjong.mode.proto.MajongPlayerData value) {
            if (playerBuilder_ == null) {
                if (value == null) {
                    throw new NullPointerException();
                }
                player_ = value;
                onChanged();
            } else {
                playerBuilder_.setMessage(value);
            }

            return this;
        }

        /**
         * <code>.majong_rpc.MajongPlayerData player = 2;</code>
         */
        public Builder setPlayer(
                mahjong.mode.proto.MajongPlayerData.Builder builderForValue) {
            if (playerBuilder_ == null) {
                player_ = builderForValue.build();
                onChanged();
            } else {
                playerBuilder_.setMessage(builderForValue.build());
            }

            return this;
        }

        /**
         * <code>.majong_rpc.MajongPlayerData player = 2;</code>
         */
        public Builder mergePlayer(mahjong.mode.proto.MajongPlayerData value) {
            if (playerBuilder_ == null) {
                if (player_ != null) {
                    player_ =
                            mahjong.mode.proto.MajongPlayerData.newBuilder(player_).mergeFrom(value).buildPartial();
                } else {
                    player_ = value;
                }
                onChanged();
            } else {
                playerBuilder_.mergeFrom(value);
            }

            return this;
        }

        /**
         * <code>.majong_rpc.MajongPlayerData player = 2;</code>
         */
        public Builder clearPlayer() {
            if (playerBuilder_ == null) {
                player_ = null;
                onChanged();
            } else {
                player_ = null;
                playerBuilder_ = null;
            }

            return this;
        }

        /**
         * <code>.majong_rpc.MajongPlayerData player = 2;</code>
         */
        public mahjong.mode.proto.MajongPlayerData.Builder getPlayerBuilder() {

            onChanged();
            return getPlayerFieldBuilder().getBuilder();
        }

        /**
         * <code>.majong_rpc.MajongPlayerData player = 2;</code>
         */
        public mahjong.mode.proto.MajongPlayerDataOrBuilder getPlayerOrBuilder() {
            if (playerBuilder_ != null) {
                return playerBuilder_.getMessageOrBuilder();
            } else {
                return player_ == null ?
                        mahjong.mode.proto.MajongPlayerData.getDefaultInstance() : player_;
            }
        }

        /**
         * <code>.majong_rpc.MajongPlayerData player = 2;</code>
         */
        private com.google.protobuf.SingleFieldBuilderV3<
                mahjong.mode.proto.MajongPlayerData, mahjong.mode.proto.MajongPlayerData.Builder, mahjong.mode.proto.MajongPlayerDataOrBuilder>
        getPlayerFieldBuilder() {
            if (playerBuilder_ == null) {
                playerBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
                        mahjong.mode.proto.MajongPlayerData, mahjong.mode.proto.MajongPlayerData.Builder, mahjong.mode.proto.MajongPlayerDataOrBuilder>(
                        getPlayer(),
                        getParentForChildren(),
                        isClean());
                player_ = null;
            }
            return playerBuilder_;
        }

        private com.google.protobuf.ByteString adjunct_ = com.google.protobuf.ByteString.EMPTY;

        /**
         * <pre>
         * 附加的一些判断条件
         * </pre>
         * <p>
         * <code>bytes adjunct = 3;</code>
         */
        public com.google.protobuf.ByteString getAdjunct() {
            return adjunct_;
        }

        /**
         * <pre>
         * 附加的一些判断条件
         * </pre>
         * <p>
         * <code>bytes adjunct = 3;</code>
         */
        public Builder setAdjunct(com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }

            adjunct_ = value;
            onChanged();
            return this;
        }

        /**
         * <pre>
         * 附加的一些判断条件
         * </pre>
         * <p>
         * <code>bytes adjunct = 3;</code>
         */
        public Builder clearAdjunct() {

            adjunct_ = getDefaultInstance().getAdjunct();
            onChanged();
            return this;
        }

        public final Builder setUnknownFields(
                final com.google.protobuf.UnknownFieldSet unknownFields) {
            return this;
        }

        public final Builder mergeUnknownFields(
                final com.google.protobuf.UnknownFieldSet unknownFields) {
            return this;
        }


        // @@protoc_insertion_point(builder_scope:majong_rpc.CalculateData)
    }

    // @@protoc_insertion_point(class_scope:majong_rpc.CalculateData)
    private static final mahjong.mode.proto.CalculateData DEFAULT_INSTANCE;

    static {
        DEFAULT_INSTANCE = new mahjong.mode.proto.CalculateData();
    }

    public static mahjong.mode.proto.CalculateData getDefaultInstance() {
        return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CalculateData>
            PARSER = new com.google.protobuf.AbstractParser<CalculateData>() {
        public CalculateData parsePartialFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return new CalculateData(input, extensionRegistry);
        }
    };

    public static com.google.protobuf.Parser<CalculateData> parser() {
        return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CalculateData> getParserForType() {
        return PARSER;
    }

    public mahjong.mode.proto.CalculateData getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
    }

}

