// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: majong_rpc.proto

package mahjong.mode.proto;

public interface CalculateDataOrBuilder extends
        // @@protoc_insertion_point(interface_extends:majong_rpc.CalculateData)
        com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 allocid = 1;</code>
     */
    int getAllocid();

    /**
     * <code>.majong_rpc.MajongPlayerData player = 2;</code>
     */
    boolean hasPlayer();

    /**
     * <code>.majong_rpc.MajongPlayerData player = 2;</code>
     */
    mahjong.mode.proto.MajongPlayerData getPlayer();

    /**
     * <code>.majong_rpc.MajongPlayerData player = 2;</code>
     */
    mahjong.mode.proto.MajongPlayerDataOrBuilder getPlayerOrBuilder();

    /**
     * <pre>
     * 附加的一些判断条件
     * </pre>
     * <p>
     * <code>bytes adjunct = 3;</code>
     */
    com.google.protobuf.ByteString getAdjunct();
}
