// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: majong_rpc.proto

package mahjong.mode.proto;

public interface CheatDataOrBuilder extends
        // @@protoc_insertion_point(interface_extends:majong_rpc.CheatData)
        com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 player_id = 1;</code>
     */
    int getPlayerId();

    /**
     * <code>int32 loc = 2;</code>
     */
    int getLoc();

    /**
     * <code>int32 level = 3;</code>
     */
    int getLevel();
}
