// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: majong_rpc.proto

package mahjong.mode.proto;

public interface MajongPlayerDataOrBuilder extends
        // @@protoc_insertion_point(interface_extends:majong_rpc.MajongPlayerData)
        com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 player_id = 1;</code>
     */
    int getPlayerId();

    /**
     * <pre>
     * 手牌
     * </pre>
     * <p>
     * <code>repeated int32 handlist = 2;</code>
     */
    java.util.List<java.lang.Integer> getHandlistList();

    /**
     * <pre>
     * 手牌
     * </pre>
     * <p>
     * <code>repeated int32 handlist = 2;</code>
     */
    int getHandlistCount();

    /**
     * <pre>
     * 手牌
     * </pre>
     * <p>
     * <code>repeated int32 handlist = 2;</code>
     */
    int getHandlist(int index);

    /**
     * <pre>
     * 吃过的牌
     * </pre>
     * <p>
     * <code>repeated int32 chi = 3;</code>
     */
    java.util.List<java.lang.Integer> getChiList();

    /**
     * <pre>
     * 吃过的牌
     * </pre>
     * <p>
     * <code>repeated int32 chi = 3;</code>
     */
    int getChiCount();

    /**
     * <pre>
     * 吃过的牌
     * </pre>
     * <p>
     * <code>repeated int32 chi = 3;</code>
     */
    int getChi(int index);

    /**
     * <pre>
     * 碰过的牌
     * </pre>
     * <p>
     * <code>repeated int32 peng = 4;</code>
     */
    java.util.List<java.lang.Integer> getPengList();

    /**
     * <pre>
     * 碰过的牌
     * </pre>
     * <p>
     * <code>repeated int32 peng = 4;</code>
     */
    int getPengCount();

    /**
     * <pre>
     * 碰过的牌
     * </pre>
     * <p>
     * <code>repeated int32 peng = 4;</code>
     */
    int getPeng(int index);

    /**
     * <pre>
     * 杠过的牌
     * </pre>
     * <p>
     * <code>repeated .majong_rpc.GangData gang = 5;</code>
     */
    java.util.List<mahjong.mode.proto.GangData>
    getGangList();

    /**
     * <pre>
     * 杠过的牌
     * </pre>
     * <p>
     * <code>repeated .majong_rpc.GangData gang = 5;</code>
     */
    mahjong.mode.proto.GangData getGang(int index);

    /**
     * <pre>
     * 杠过的牌
     * </pre>
     * <p>
     * <code>repeated .majong_rpc.GangData gang = 5;</code>
     */
    int getGangCount();

    /**
     * <pre>
     * 杠过的牌
     * </pre>
     * <p>
     * <code>repeated .majong_rpc.GangData gang = 5;</code>
     */
    java.util.List<? extends mahjong.mode.proto.GangDataOrBuilder>
    getGangOrBuilderList();

    /**
     * <pre>
     * 杠过的牌
     * </pre>
     * <p>
     * <code>repeated .majong_rpc.GangData gang = 5;</code>
     */
    mahjong.mode.proto.GangDataOrBuilder getGangOrBuilder(
            int index);
}
