// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: majong_rpc.proto

package mahjong.mode.proto;

public final class MajongRpcProto {
    private MajongRpcProto() {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions(
                (com.google.protobuf.ExtensionRegistryLite) registry);
    }

    static final com.google.protobuf.Descriptors.Descriptor
            internal_static_majong_rpc_GangData_descriptor;
    static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_majong_rpc_GangData_fieldAccessorTable;
    static final com.google.protobuf.Descriptors.Descriptor
            internal_static_majong_rpc_MajongPlayerData_descriptor;
    static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_majong_rpc_MajongPlayerData_fieldAccessorTable;
    static final com.google.protobuf.Descriptors.Descriptor
            internal_static_majong_rpc_CalculateData_descriptor;
    static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_majong_rpc_CalculateData_fieldAccessorTable;
    static final com.google.protobuf.Descriptors.Descriptor
            internal_static_majong_rpc_CalculateResult_descriptor;
    static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_majong_rpc_CalculateResult_fieldAccessorTable;
    static final com.google.protobuf.Descriptors.Descriptor
            internal_static_majong_rpc_SettlePlayerData_descriptor;
    static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_majong_rpc_SettlePlayerData_fieldAccessorTable;
    static final com.google.protobuf.Descriptors.Descriptor
            internal_static_majong_rpc_SettleData_descriptor;
    static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_majong_rpc_SettleData_fieldAccessorTable;
    static final com.google.protobuf.Descriptors.Descriptor
            internal_static_majong_rpc_SettleResult_descriptor;
    static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_majong_rpc_SettleResult_fieldAccessorTable;
    static final com.google.protobuf.Descriptors.Descriptor
            internal_static_majong_rpc_CheatData_descriptor;
    static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_majong_rpc_CheatData_fieldAccessorTable;
    static final com.google.protobuf.Descriptors.Descriptor
            internal_static_majong_rpc_ShuffleData_descriptor;
    static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_majong_rpc_ShuffleData_fieldAccessorTable;
    static final com.google.protobuf.Descriptors.Descriptor
            internal_static_majong_rpc_ShuffleResult_descriptor;
    static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_majong_rpc_ShuffleResult_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }

    private static com.google.protobuf.Descriptors.FileDescriptor
            descriptor;

    static {
        java.lang.String[] descriptorData = {
                "\n\020majong_rpc.proto\022\nmajong_rpc\"R\n\010GangDa" +
                        "ta\022\"\n\004type\030\001 \001(\0162\024.majong_rpc.GangType\022\017" +
                        "\n\007fighter\030\002 \001(\005\022\021\n\tgangvalue\030\003 \001(\005\"v\n\020Ma" +
                        "jongPlayerData\022\021\n\tplayer_id\030\001 \001(\005\022\020\n\010han" +
                        "dlist\030\002 \003(\005\022\013\n\003chi\030\003 \003(\005\022\014\n\004peng\030\004 \003(\005\022\"" +
                        "\n\004gang\030\005 \003(\0132\024.majong_rpc.GangData\"_\n\rCa" +
                        "lculateData\022\017\n\007allocid\030\001 \001(\005\022,\n\006player\030\002" +
                        " \001(\0132\034.majong_rpc.MajongPlayerData\022\017\n\007ad" +
                        "junct\030\003 \001(\014\"e\n\017CalculateResult\022\013\n\003chi\030\001 " +
                        "\003(\005\022\014\n\004peng\030\002 \003(\005\022\014\n\004gang\030\003 \003(\005\022\n\n\002hu\030\004 ",
                "\003(\005\022\014\n\004zimo\030\005 \003(\005\022\017\n\007adjunct\030\006 \001(\014\"\211\001\n\020S" +
                        "ettlePlayerData\022,\n\006player\030\001 \001(\0132\034.majong" +
                        "_rpc.MajongPlayerData\022&\n\006settle\030\002 \001(\0162\026." +
                        "majong_rpc.SettleType\022\016\n\006majong\030\003 \001(\005\022\017\n" +
                        "\007adjunct\030\004 \001(\014\"\234\001\n\nSettleData\022\020\n\010alloc_i" +
                        "d\030\001 \001(\005\0221\n\013player_list\030\002 \003(\0132\034.majong_rp" +
                        "c.SettlePlayerData\022\022\n\ngang_combo\030\003 \001(\005\022\016" +
                        "\n\006banker\030\004 \001(\005\022\024\n\014banker_combo\030\005 \001(\005\022\017\n\007" +
                        "adjunct\030\006 \001(\014\"\037\n\014SettleResult\022\017\n\007results" +
                        "\030\001 \001(\014\":\n\tCheatData\022\021\n\tplayer_id\030\001 \001(\005\022\013",
                "\n\003loc\030\002 \001(\005\022\r\n\005level\030\003 \001(\005\"W\n\013ShuffleDat" +
                        "a\022\020\n\010alloc_id\030\001 \001(\005\022%\n\006cheats\030\002 \003(\0132\025.ma" +
                        "jong_rpc.CheatData\022\017\n\007adjunct\030\003 \001(\014\" \n\rS" +
                        "huffleResult\022\017\n\007majongs\030\001 \001(\014*+\n\010GangTyp" +
                        "e\022\t\n\005BGANG\020\000\022\t\n\005MGANG\020\001\022\t\n\005AGANG\020\002*\247\001\n\nS" +
                        "ettleType\022\013\n\007PING_JU\020\000\022\014\n\010FANG_PAO\020\001\022\n\n\006" +
                        "HU_PAO\020\002\022\t\n\005ZI_MO\020\003\022\n\n\006BZI_MO\020\004\022\014\n\010GANG_" +
                        "PAO\020\005\022\017\n\013HU_GANG_PAO\020\006\022\014\n\010GANG_HUA\020\007\022\r\n\t" +
                        "BGANG_HUA\020\010\022\016\n\nQIANG_GANG\020\t\022\017\n\013BQIANG_GA" +
                        "NG\020\n2\327\001\n\017MajongCalculate\022E\n\tcalculate\022\031.",
                "majong_rpc.CalculateData\032\033.majong_rpc.Ca" +
                        "lculateResult\"\000\022<\n\006settle\022\026.majong_rpc.S" +
                        "ettleData\032\030.majong_rpc.SettleResult\"\000\022?\n" +
                        "\007shuffle\022\027.majong_rpc.ShuffleData\032\031.majo" +
                        "ng_rpc.ShuffleResult\"\000B,\n\022mahjong.mode.p" +
                        "rotoB\016MajongRpcProtoP\001\242\002\003HLWb\006proto3"
        };
        com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
                new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
                    public com.google.protobuf.ExtensionRegistry assignDescriptors(
                            com.google.protobuf.Descriptors.FileDescriptor root) {
                        descriptor = root;
                        return null;
                    }
                };
        com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[]{
                        }, assigner);
        internal_static_majong_rpc_GangData_descriptor =
                getDescriptor().getMessageTypes().get(0);
        internal_static_majong_rpc_GangData_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_majong_rpc_GangData_descriptor,
                new java.lang.String[]{"Type", "Fighter", "Gangvalue",});
        internal_static_majong_rpc_MajongPlayerData_descriptor =
                getDescriptor().getMessageTypes().get(1);
        internal_static_majong_rpc_MajongPlayerData_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_majong_rpc_MajongPlayerData_descriptor,
                new java.lang.String[]{"PlayerId", "Handlist", "Chi", "Peng", "Gang",});
        internal_static_majong_rpc_CalculateData_descriptor =
                getDescriptor().getMessageTypes().get(2);
        internal_static_majong_rpc_CalculateData_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_majong_rpc_CalculateData_descriptor,
                new java.lang.String[]{"Allocid", "Player", "Adjunct",});
        internal_static_majong_rpc_CalculateResult_descriptor =
                getDescriptor().getMessageTypes().get(3);
        internal_static_majong_rpc_CalculateResult_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_majong_rpc_CalculateResult_descriptor,
                new java.lang.String[]{"Chi", "Peng", "Gang", "Hu", "Zimo", "Adjunct",});
        internal_static_majong_rpc_SettlePlayerData_descriptor =
                getDescriptor().getMessageTypes().get(4);
        internal_static_majong_rpc_SettlePlayerData_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_majong_rpc_SettlePlayerData_descriptor,
                new java.lang.String[]{"Player", "Settle", "Majong", "Adjunct",});
        internal_static_majong_rpc_SettleData_descriptor =
                getDescriptor().getMessageTypes().get(5);
        internal_static_majong_rpc_SettleData_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_majong_rpc_SettleData_descriptor,
                new java.lang.String[]{"AllocId", "PlayerList", "GangCombo", "Banker", "BankerCombo", "Adjunct",});
        internal_static_majong_rpc_SettleResult_descriptor =
                getDescriptor().getMessageTypes().get(6);
        internal_static_majong_rpc_SettleResult_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_majong_rpc_SettleResult_descriptor,
                new java.lang.String[]{"Results",});
        internal_static_majong_rpc_CheatData_descriptor =
                getDescriptor().getMessageTypes().get(7);
        internal_static_majong_rpc_CheatData_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_majong_rpc_CheatData_descriptor,
                new java.lang.String[]{"PlayerId", "Loc", "Level",});
        internal_static_majong_rpc_ShuffleData_descriptor =
                getDescriptor().getMessageTypes().get(8);
        internal_static_majong_rpc_ShuffleData_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_majong_rpc_ShuffleData_descriptor,
                new java.lang.String[]{"AllocId", "Cheats", "Adjunct",});
        internal_static_majong_rpc_ShuffleResult_descriptor =
                getDescriptor().getMessageTypes().get(9);
        internal_static_majong_rpc_ShuffleResult_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_majong_rpc_ShuffleResult_descriptor,
                new java.lang.String[]{"Majongs",});
    }

    // @@protoc_insertion_point(outer_class_scope)
}
