// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: majong_rpc.proto

package mahjong.mode.proto;

public interface SettlePlayerDataOrBuilder extends
        // @@protoc_insertion_point(interface_extends:majong_rpc.SettlePlayerData)
        com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.majong_rpc.MajongPlayerData player = 1;</code>
     */
    boolean hasPlayer();

    /**
     * <code>.majong_rpc.MajongPlayerData player = 1;</code>
     */
    mahjong.mode.proto.MajongPlayerData getPlayer();

    /**
     * <code>.majong_rpc.MajongPlayerData player = 1;</code>
     */
    mahjong.mode.proto.MajongPlayerDataOrBuilder getPlayerOrBuilder();

    /**
     * <code>.majong_rpc.SettleType settle = 2;</code>
     */
    int getSettleValue();

    /**
     * <code>.majong_rpc.SettleType settle = 2;</code>
     */
    mahjong.mode.proto.SettleType getSettle();

    /**
     * <pre>
     * 胡的哪张牌
     * </pre>
     * <p>
     * <code>int32 majong = 3;</code>
     */
    int getMajong();

    /**
     * <pre>
     * 附加数据，用于一些特殊需求的麻将
     * </pre>
     * <p>
     * <code>bytes adjunct = 4;</code>
     */
    com.google.protobuf.ByteString getAdjunct();
}
