// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: majong_rpc.proto

package mahjong.mode.proto;

public interface ShuffleResultOrBuilder extends
        // @@protoc_insertion_point(interface_extends:majong_rpc.ShuffleResult)
        com.google.protobuf.MessageOrBuilder {

    /**
     * <code>bytes majongs = 1;</code>
     */
    com.google.protobuf.ByteString getMajongs();
}
