// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: majong_rpc.proto

package mahjong.mode.proto;

public interface ShuffleDataOrBuilder extends
        // @@protoc_insertion_point(interface_extends:majong_rpc.ShuffleData)
        com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 alloc_id = 1;</code>
     */
    int getAllocId();

    /**
     * <code>repeated .majong_rpc.CheatData cheats = 2;</code>
     */
    java.util.List<mahjong.mode.proto.CheatData>
    getCheatsList();

    /**
     * <code>repeated .majong_rpc.CheatData cheats = 2;</code>
     */
    mahjong.mode.proto.CheatData getCheats(int index);

    /**
     * <code>repeated .majong_rpc.CheatData cheats = 2;</code>
     */
    int getCheatsCount();

    /**
     * <code>repeated .majong_rpc.CheatData cheats = 2;</code>
     */
    java.util.List<? extends mahjong.mode.proto.CheatDataOrBuilder>
    getCheatsOrBuilderList();

    /**
     * <code>repeated .majong_rpc.CheatData cheats = 2;</code>
     */
    mahjong.mode.proto.CheatDataOrBuilder getCheatsOrBuilder(
            int index);

    /**
     * <code>bytes adjunct = 3;</code>
     */
    com.google.protobuf.ByteString getAdjunct();
}
