// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SJ_mahjong.proto

package mahjong.mode.proto;

public interface SjApplyCalculateDataOrBuilder extends
        // @@protoc_insertion_point(interface_extends:wh_majong.SjApplyCalculateData)
        com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 是否旋风杠
     * </pre>
     * <p>
     * <code>bool xuanfeng = 1;</code>
     */
    boolean getXuanfeng();

    /**
     * <pre>
     * 是否已经旋风杠 1为中发白的旋风杠，2为东南西北的旋风杠
     * </pre>
     * <p>
     * <code>repeated int32 xflist = 2;</code>
     */
    java.util.List<java.lang.Integer> getXflistList();

    /**
     * <pre>
     * 是否已经旋风杠 1为中发白的旋风杠，2为东南西北的旋风杠
     * </pre>
     * <p>
     * <code>repeated int32 xflist = 2;</code>
     */
    int getXflistCount();

    /**
     * <pre>
     * 是否已经旋风杠 1为中发白的旋风杠，2为东南西北的旋风杠
     * </pre>
     * <p>
     * <code>repeated int32 xflist = 2;</code>
     */
    int getXflist(int index);

    /**
     * <pre>
     * 一番封顶
     * </pre>
     * <p>
     * <code>bool yifan = 3;</code>
     */
    boolean getYifan();
}
