// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SJ_mahjong.proto

package mahjong.mode.proto;

public final class SJMahjong {
    private SJMahjong() {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions(
                (com.google.protobuf.ExtensionRegistryLite) registry);
    }

    static final com.google.protobuf.Descriptors.Descriptor
            internal_static_wh_majong_SjApplyCalculateData_descriptor;
    static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_wh_majong_SjApplyCalculateData_fieldAccessorTable;
    static final com.google.protobuf.Descriptors.Descriptor
            internal_static_wh_majong_SjPlayerSettleData_descriptor;
    static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_wh_majong_SjPlayerSettleData_fieldAccessorTable;
    static final com.google.protobuf.Descriptors.Descriptor
            internal_static_wh_majong_SjApplySettleData_descriptor;
    static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_wh_majong_SjApplySettleData_fieldAccessorTable;
    static final com.google.protobuf.Descriptors.Descriptor
            internal_static_wh_majong_SjSingleSettleResult_descriptor;
    static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_wh_majong_SjSingleSettleResult_fieldAccessorTable;
    static final com.google.protobuf.Descriptors.Descriptor
            internal_static_wh_majong_SjSettleResult_descriptor;
    static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_wh_majong_SjSettleResult_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }

    private static com.google.protobuf.Descriptors.FileDescriptor
            descriptor;

    static {
        java.lang.String[] descriptorData = {
                "\n\020SJ_mahjong.proto\022\twh_majong\"G\n\024SjApply" +
                        "CalculateData\022\020\n\010xuanfeng\030\001 \001(\010\022\016\n\006xflis" +
                        "t\030\002 \003(\005\022\r\n\005yifan\030\003 \001(\010\"$\n\022SjPlayerSettle" +
                        "Data\022\016\n\006xflist\030\001 \003(\005\"P\n\021SjApplySettleDat" +
                        "a\022\020\n\010xuanfeng\030\001 \001(\010\022\016\n\006normal\030\002 \001(\010\022\013\n\003t" +
                        "op\030\003 \001(\005\022\014\n\004piao\030\004 \001(\005\"\271\001\n\024SjSingleSettl" +
                        "eResult\022\021\n\tplayer_id\030\001 \001(\005\022\022\n\nbase_score" +
                        "\030\002 \001(\005\022\022\n\ngang_score\030\003 \001(\005\022\023\n\013total_scor" +
                        "e\030\004 \001(\005\022-\n\010patterns\030\005 \003(\0162\033.wh_majong.Sj" +
                        "SettlePatterns\022\013\n\003fan\030\006 \001(\005\022\025\n\rgang_hu_s",
                "core\030\007 \001(\005\"B\n\016SjSettleResult\0220\n\007results\030" +
                        "\001 \003(\0132\037.wh_majong.SjSingleSettleResult*\216" +
                        "\002\n\020SjSettlePatterns\022\n\n\006ANTING\020\000\022\016\n\nPENGP" +
                        "ENGHU\020\001\022\t\n\005LIMEN\020\002\022\013\n\007HUNYISE\020\003\022\014\n\010SHOUB" +
                        "AYI\020\004\022\016\n\nGANGHOUFAN\020\005\022\014\n\010QINGYISE\020\006\022\014\n\010Y" +
                        "IBANGAO\020\007\022\013\n\007SIGUIYI\020\010\022\r\n\tSHISANYAO\020\t\022\016\n" +
                        "\nSANJIAQING\020\n\022\r\n\tSIJIAQING\020\013\022\t\n\005QIDUI\020\014\022" +
                        "\013\n\007DIANPAO\020\r\022\010\n\004ZIMO\020\016\022\r\n\tZUOZHUANG\020\017\022\020\n" +
                        "\014XUANFENGGANG\020\020\022\016\n\nGANGHOUPAO\020\021B\034\n\022mahjo" +
                        "ng.mode.protoP\001\242\002\003HLWb\006proto3"
        };
        com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
                new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
                    public com.google.protobuf.ExtensionRegistry assignDescriptors(
                            com.google.protobuf.Descriptors.FileDescriptor root) {
                        descriptor = root;
                        return null;
                    }
                };
        com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[]{
                        }, assigner);
        internal_static_wh_majong_SjApplyCalculateData_descriptor =
                getDescriptor().getMessageTypes().get(0);
        internal_static_wh_majong_SjApplyCalculateData_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_wh_majong_SjApplyCalculateData_descriptor,
                new java.lang.String[]{"Xuanfeng", "Xflist", "Yifan",});
        internal_static_wh_majong_SjPlayerSettleData_descriptor =
                getDescriptor().getMessageTypes().get(1);
        internal_static_wh_majong_SjPlayerSettleData_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_wh_majong_SjPlayerSettleData_descriptor,
                new java.lang.String[]{"Xflist",});
        internal_static_wh_majong_SjApplySettleData_descriptor =
                getDescriptor().getMessageTypes().get(2);
        internal_static_wh_majong_SjApplySettleData_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_wh_majong_SjApplySettleData_descriptor,
                new java.lang.String[]{"Xuanfeng", "Normal", "Top", "Piao",});
        internal_static_wh_majong_SjSingleSettleResult_descriptor =
                getDescriptor().getMessageTypes().get(3);
        internal_static_wh_majong_SjSingleSettleResult_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_wh_majong_SjSingleSettleResult_descriptor,
                new java.lang.String[]{"PlayerId", "BaseScore", "GangScore", "TotalScore", "Patterns", "Fan", "GangHuScore",});
        internal_static_wh_majong_SjSettleResult_descriptor =
                getDescriptor().getMessageTypes().get(4);
        internal_static_wh_majong_SjSettleResult_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_wh_majong_SjSettleResult_descriptor,
                new java.lang.String[]{"Results",});
    }

    // @@protoc_insertion_point(outer_class_scope)
}
