// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SJ_mahjong.proto

package mahjong.mode.proto;

public interface SjPlayerSettleDataOrBuilder extends
        // @@protoc_insertion_point(interface_extends:wh_majong.SjPlayerSettleData)
        com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 这里是包含了旋风杠本身的牌和补杠的牌
     * </pre>
     * <p>
     * <code>repeated int32 xflist = 1;</code>
     */
    java.util.List<java.lang.Integer> getXflistList();

    /**
     * <pre>
     * 这里是包含了旋风杠本身的牌和补杠的牌
     * </pre>
     * <p>
     * <code>repeated int32 xflist = 1;</code>
     */
    int getXflistCount();

    /**
     * <pre>
     * 这里是包含了旋风杠本身的牌和补杠的牌
     * </pre>
     * <p>
     * <code>repeated int32 xflist = 1;</code>
     */
    int getXflist(int index);
}
