// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SJ_mahjong.proto

package mahjong.mode.proto;

public interface SjSettleResultOrBuilder extends
        // @@protoc_insertion_point(interface_extends:wh_majong.SjSettleResult)
        com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 结果数组
     * </pre>
     * <p>
     * <code>repeated .wh_majong.SjSingleSettleResult results = 1;</code>
     */
    java.util.List<mahjong.mode.proto.SjSingleSettleResult>
    getResultsList();

    /**
     * <pre>
     * 结果数组
     * </pre>
     * <p>
     * <code>repeated .wh_majong.SjSingleSettleResult results = 1;</code>
     */
    mahjong.mode.proto.SjSingleSettleResult getResults(int index);

    /**
     * <pre>
     * 结果数组
     * </pre>
     * <p>
     * <code>repeated .wh_majong.SjSingleSettleResult results = 1;</code>
     */
    int getResultsCount();

    /**
     * <pre>
     * 结果数组
     * </pre>
     * <p>
     * <code>repeated .wh_majong.SjSingleSettleResult results = 1;</code>
     */
    java.util.List<? extends mahjong.mode.proto.SjSingleSettleResultOrBuilder>
    getResultsOrBuilderList();

    /**
     * <pre>
     * 结果数组
     * </pre>
     * <p>
     * <code>repeated .wh_majong.SjSingleSettleResult results = 1;</code>
     */
    mahjong.mode.proto.SjSingleSettleResultOrBuilder getResultsOrBuilder(
            int index);
}
