// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SJ_mahjong.proto

package mahjong.mode.proto;

/**
 * Protobuf enum {@code wh_majong.SjSettlePatterns}
 */
public enum SjSettlePatterns
        implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <pre>
     * 暗听
     * </pre>
     * <p>
     * <code>ANTING = 0;</code>
     */
    ANTING(0),
    /**
     * <pre>
     * 碰碰胡
     * </pre>
     * <p>
     * <code>PENGPENGHU = 1;</code>
     */
    PENGPENGHU(1),
    /**
     * <pre>
     * 立门
     * </pre>
     * <p>
     * <code>LIMEN = 2;</code>
     */
    LIMEN(2),
    /**
     * <pre>
     * 混一色
     * </pre>
     * <p>
     * <code>HUNYISE = 3;</code>
     */
    HUNYISE(3),
    /**
     * <pre>
     * 手把一
     * </pre>
     * <p>
     * <code>SHOUBAYI = 4;</code>
     */
    SHOUBAYI(4),
    /**
     * <pre>
     * 杠后翻
     * </pre>
     * <p>
     * <code>GANGHOUFAN = 5;</code>
     */
    GANGHOUFAN(5),
    /**
     * <pre>
     * 清一色
     * </pre>
     * <p>
     * <code>QINGYISE = 6;</code>
     */
    QINGYISE(6),
    /**
     * <pre>
     * 一般高
     * </pre>
     * <p>
     * <code>YIBANGAO = 7;</code>
     */
    YIBANGAO(7),
    /**
     * <pre>
     * 四归一
     * </pre>
     * <p>
     * <code>SIGUIYI = 8;</code>
     */
    SIGUIYI(8),
    /**
     * <pre>
     * 十三幺
     * </pre>
     * <p>
     * <code>SHISANYAO = 9;</code>
     */
    SHISANYAO(9),
    /**
     * <pre>
     * 三家清
     * </pre>
     * <p>
     * <code>SANJIAQING = 10;</code>
     */
    SANJIAQING(10),
    /**
     * <pre>
     * 四家清
     * </pre>
     * <p>
     * <code>SIJIAQING = 11;</code>
     */
    SIJIAQING(11),
    /**
     * <pre>
     * 七对
     * </pre>
     * <p>
     * <code>QIDUI = 12;</code>
     */
    QIDUI(12),
    /**
     * <pre>
     * 点炮
     * </pre>
     * <p>
     * <code>DIANPAO = 13;</code>
     */
    DIANPAO(13),
    /**
     * <pre>
     * 自摸
     * </pre>
     * <p>
     * <code>ZIMO = 14;</code>
     */
    ZIMO(14),
    /**
     * <pre>
     * 坐庄
     * </pre>
     * <p>
     * <code>ZUOZHUANG = 15;</code>
     */
    ZUOZHUANG(15),
    /**
     * <pre>
     * 旋风杠
     * </pre>
     * <p>
     * <code>XUANFENGGANG = 16;</code>
     */
    XUANFENGGANG(16),
    /**
     * <pre>
     * 杠后炮
     * </pre>
     * <p>
     * <code>GANGHOUPAO = 17;</code>
     */
    GANGHOUPAO(17),
    UNRECOGNIZED(-1),;

    /**
     * <pre>
     * 暗听
     * </pre>
     * <p>
     * <code>ANTING = 0;</code>
     */
    public static final int ANTING_VALUE = 0;
    /**
     * <pre>
     * 碰碰胡
     * </pre>
     * <p>
     * <code>PENGPENGHU = 1;</code>
     */
    public static final int PENGPENGHU_VALUE = 1;
    /**
     * <pre>
     * 立门
     * </pre>
     * <p>
     * <code>LIMEN = 2;</code>
     */
    public static final int LIMEN_VALUE = 2;
    /**
     * <pre>
     * 混一色
     * </pre>
     * <p>
     * <code>HUNYISE = 3;</code>
     */
    public static final int HUNYISE_VALUE = 3;
    /**
     * <pre>
     * 手把一
     * </pre>
     * <p>
     * <code>SHOUBAYI = 4;</code>
     */
    public static final int SHOUBAYI_VALUE = 4;
    /**
     * <pre>
     * 杠后翻
     * </pre>
     * <p>
     * <code>GANGHOUFAN = 5;</code>
     */
    public static final int GANGHOUFAN_VALUE = 5;
    /**
     * <pre>
     * 清一色
     * </pre>
     * <p>
     * <code>QINGYISE = 6;</code>
     */
    public static final int QINGYISE_VALUE = 6;
    /**
     * <pre>
     * 一般高
     * </pre>
     * <p>
     * <code>YIBANGAO = 7;</code>
     */
    public static final int YIBANGAO_VALUE = 7;
    /**
     * <pre>
     * 四归一
     * </pre>
     * <p>
     * <code>SIGUIYI = 8;</code>
     */
    public static final int SIGUIYI_VALUE = 8;
    /**
     * <pre>
     * 十三幺
     * </pre>
     * <p>
     * <code>SHISANYAO = 9;</code>
     */
    public static final int SHISANYAO_VALUE = 9;
    /**
     * <pre>
     * 三家清
     * </pre>
     * <p>
     * <code>SANJIAQING = 10;</code>
     */
    public static final int SANJIAQING_VALUE = 10;
    /**
     * <pre>
     * 四家清
     * </pre>
     * <p>
     * <code>SIJIAQING = 11;</code>
     */
    public static final int SIJIAQING_VALUE = 11;
    /**
     * <pre>
     * 七对
     * </pre>
     * <p>
     * <code>QIDUI = 12;</code>
     */
    public static final int QIDUI_VALUE = 12;
    /**
     * <pre>
     * 点炮
     * </pre>
     * <p>
     * <code>DIANPAO = 13;</code>
     */
    public static final int DIANPAO_VALUE = 13;
    /**
     * <pre>
     * 自摸
     * </pre>
     * <p>
     * <code>ZIMO = 14;</code>
     */
    public static final int ZIMO_VALUE = 14;
    /**
     * <pre>
     * 坐庄
     * </pre>
     * <p>
     * <code>ZUOZHUANG = 15;</code>
     */
    public static final int ZUOZHUANG_VALUE = 15;
    /**
     * <pre>
     * 旋风杠
     * </pre>
     * <p>
     * <code>XUANFENGGANG = 16;</code>
     */
    public static final int XUANFENGGANG_VALUE = 16;
    /**
     * <pre>
     * 杠后炮
     * </pre>
     * <p>
     * <code>GANGHOUPAO = 17;</code>
     */
    public static final int GANGHOUPAO_VALUE = 17;


    public final int getNumber() {
        if (this == UNRECOGNIZED) {
            throw new java.lang.IllegalArgumentException(
                    "Can't get the number of an unknown enum value.");
        }
        return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static SjSettlePatterns valueOf(int value) {
        return forNumber(value);
    }

    public static SjSettlePatterns forNumber(int value) {
        switch (value) {
            case 0:
                return ANTING;
            case 1:
                return PENGPENGHU;
            case 2:
                return LIMEN;
            case 3:
                return HUNYISE;
            case 4:
                return SHOUBAYI;
            case 5:
                return GANGHOUFAN;
            case 6:
                return QINGYISE;
            case 7:
                return YIBANGAO;
            case 8:
                return SIGUIYI;
            case 9:
                return SHISANYAO;
            case 10:
                return SANJIAQING;
            case 11:
                return SIJIAQING;
            case 12:
                return QIDUI;
            case 13:
                return DIANPAO;
            case 14:
                return ZIMO;
            case 15:
                return ZUOZHUANG;
            case 16:
                return XUANFENGGANG;
            case 17:
                return GANGHOUPAO;
            default:
                return null;
        }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<SjSettlePatterns>
    internalGetValueMap() {
        return internalValueMap;
    }

    private static final com.google.protobuf.Internal.EnumLiteMap<
            SjSettlePatterns> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<SjSettlePatterns>() {
                public SjSettlePatterns findValueByNumber(int number) {
                    return SjSettlePatterns.forNumber(number);
                }
            };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
    getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
    }

    public final com.google.protobuf.Descriptors.EnumDescriptor
    getDescriptorForType() {
        return getDescriptor();
    }

    public static final com.google.protobuf.Descriptors.EnumDescriptor
    getDescriptor() {
        return mahjong.mode.proto.SJMahjong.getDescriptor().getEnumTypes().get(0);
    }

    private static final SjSettlePatterns[] VALUES = values();

    public static SjSettlePatterns valueOf(
            com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
                    "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
            return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
    }

    private final int value;

    private SjSettlePatterns(int value) {
        this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:wh_majong.SjSettlePatterns)
}

