// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SJ_mahjong.proto

package mahjong.mode.proto;

public interface SjSingleSettleResultOrBuilder extends
        // @@protoc_insertion_point(interface_extends:wh_majong.SjSingleSettleResult)
        com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 玩家ID
     * </pre>
     * <p>
     * <code>int32 player_id = 1;</code>
     */
    int getPlayerId();

    /**
     * <pre>
     * 基础牌型分
     * </pre>
     * <p>
     * <code>int32 base_score = 2;</code>
     */
    int getBaseScore();

    /**
     * <pre>
     * 杠分
     * </pre>
     * <p>
     * <code>int32 gang_score = 3;</code>
     */
    int getGangScore();

    /**
     * <pre>
     * 总得分
     * </pre>
     * <p>
     * <code>int32 total_score = 4;</code>
     */
    int getTotalScore();

    /**
     * <pre>
     * 牌型结算
     * </pre>
     * <p>
     * <code>repeated .wh_majong.SjSettlePatterns patterns = 5;</code>
     */
    java.util.List<mahjong.mode.proto.SjSettlePatterns> getPatternsList();

    /**
     * <pre>
     * 牌型结算
     * </pre>
     * <p>
     * <code>repeated .wh_majong.SjSettlePatterns patterns = 5;</code>
     */
    int getPatternsCount();

    /**
     * <pre>
     * 牌型结算
     * </pre>
     * <p>
     * <code>repeated .wh_majong.SjSettlePatterns patterns = 5;</code>
     */
    mahjong.mode.proto.SjSettlePatterns getPatterns(int index);

    /**
     * <pre>
     * 牌型结算
     * </pre>
     * <p>
     * <code>repeated .wh_majong.SjSettlePatterns patterns = 5;</code>
     */
    java.util.List<java.lang.Integer>
    getPatternsValueList();

    /**
     * <pre>
     * 牌型结算
     * </pre>
     * <p>
     * <code>repeated .wh_majong.SjSettlePatterns patterns = 5;</code>
     */
    int getPatternsValue(int index);

    /**
     * <pre>
     * 番数
     * </pre>
     * <p>
     * <code>int32 fan = 6;</code>
     */
    int getFan();

    /**
     * <pre>
     * 杠胡分
     * </pre>
     * <p>
     * <code>int32 gang_hu_score = 7;</code>
     */
    int getGangHuScore();
}
